tests:
  input-echo-standard:
    image: ghcr.io/vliz-be-opsci/grmp-test-implementations-input-echo-test:main
    config:
      url: https://brugge-ldes.geomobility.eu/observations
      max-redirects: 3
      timeout: 10
      check-http-availability: false
      check-https-availability: true
    
  input-echo-standard-2:
    image: ghcr.io/vliz-be-opsci/grmp-test-implementations-input-echo-test:main
    config:
      url: https://brugge-ldes.geomobility.eu/observations
      supports-content-types:
        - text/turtle
        - application/trig
      check-response-body-conformity: true

  input-echo-fail:
    image: ghcr.io/vliz-be-opsci/grmp-test-implementations-input-echo-test:main
    config:
      url:
      supports-content-types:
        - text/turtle
        - application/trig
      check-response-body-conformity: true

  input-echo-skip:
    image: ghcr.io/vliz-be-opsci/grmp-test-implementations-input-echo-test:main
    config:
