tests:
  input-echo-standard:
    image: ghcr.io/vliz-be-opsci/grmp-test-implementations-input-echo-test:main
    config:
      url: https://brugge-ldes.geomobility.eu/observations
      max-redirects: 3
      timeout: 10
      check-http-availability: false
      check-https-availability: true
    
  input-echo-alice:
    image: ghcr.io/vliz-be-opsci/grmp-test-implementations-input-echo-test:main
    config:
      supports-content-types:
        - application/trig
      check-response-body-conformity: true